pJanks/jeopardy

data/dataset.js
src/Clue.js
src/Game.js
src/Player.js
src/Round.js
src/index.js
test/Clue-test.js

Build out initial classes<br>
Review tests for clue class<br>
Pull down changes and run npm test in the console<br>
We need to build out the other classes.

Building classes

---

src/main.js

This refactors some JS into jQuery syntax.<br>
Review the changes in the code.<br>
Pull down changes and check for bugs.<br>
We need to rethink our approach to DOM manipulation.

Refactor js to jquery

---

src/Game.js
src/domUpdates.js
src/index.js
src/main.js

This will reorganize our DOM manipulation files as well as get the dataset and make it accessible to the Game class.<br>
Review the code.<br>
Pull down the changes to check for bugs<br>
We can now focus on instantiating players.

Fetching data

---

src/Clue.js
src/Payer.js
test/clue-test.js
test/game-test.js
test/player-test.js

Adds test for the game and clue class.
Run a test for the game and clue classes
Insure the all game and clue test pass
Will need to add additional test as methods are added

Test files

---

test/clue-test.js

Remove file

---

src/domUpdates.js

This ensures that three unique rounds are created with the correct daily double counts.
Review the domUpdates.js startGame method. 
Pull down changes and check for bugs or any broken behavior.
- We should evaluate each file and make sure the correct methods are living in the correct classes.
- We should also reaffirm that our tests are robust and free of false positives(especially Game-test.js).
@khalidwilliams
@hannahhch

Create all three necessary rounds

---

src/Game.js
src/domUpdates.js

I am not yet creating instances of Clues, but I am able to get the clues from the dataset. I think it will be an easy fix. I am also sorting them into an ascending order so it should work well with DOM manipulation.
Review the changes in the Game.js file and see if you find any errors or console.logs left over.
Pull down the branch and log the Round's clues. It should be a unique list with only one clue for each point value from each subject.
We need to populate the DOM with this info. I also think there is a better way to do this logic, but I know it works now. We should considering refactoring after we have an MVP.
@khalidwilliams
@hannahhch

Instantiate clues

---

src/css/base.scss
src/index.html

Update to our newest theme, STAR WARS JEOPARDY 1977!
Pull down an check functionality for start of game
Test player name inputs and viewing game board
Need to refactor sizing of game board

Setup start game & Refactor Theme

---

src/Game.js
src/domUpdates.js
src/index.js

This PR adds a catch to our fetch method as well as refactors some of the methods. I took things out of our domUpdates file and added them top the Game file because it makes more sense for them to live there. We are also taking the clue objects from the dataset and creating instances of our Clue class so that they have access to its methods.
- Please review the populateGameBoard method on domUpdates, as well as the methods I added to the Game class.
- Also, since the page is fixed I would appreciate feedback on the tests.
Pull down changes and check for buggy or broken behavior. This version of the game should compile correctly.
The next step for me is getting the clues to populate on the DOM in the right place.
@khalidwilliams 
@hannahhch

Refactoring methods

---

src/Game.js
src/index.js

This fixes bugs within the catch on our fetch method, and randomizes the allClues array so that we get different questions for each category every time the page loads.
Review the code and pay close attention to the method that randomizes the clues in the Game class.
Pull down changes and check for bugs.
We need to populate the DOM with questions specific to where the click event happens.

Catch bugs

---

src/css/base.scss
src/domUpdates.js
src/index.html

Change display of possible answers to clues.
Start game and select a box on game board.
Test hovering over each possible answer.
Need to refactor start screen too.

Add character icons

---

src/domUpdates.js

I am getting the incorrect answers to populate correctly when a user clicks on a specific box. I also have that point value leaving the DOM and that box becoming disabled.
This logic is happening in the printSingleQuestion method on domUpdates.
Pull down the changes and check for buggy behavior.
We need to add functionality for choosing correct or incorrect answers.

Getting specific questions

---

src/Game.js
src/domUpdates.js

This is getting clear separation of rounds one and two, as well as getting the players to change after each question.
Review the domUpdates and Game class.
Pull down changes and check for bugs or broken behavior.
We need to add behavior for a user choosing an incorrect/correct answer.

Getting rounds to change

---

src/domUpdates.js
src/index.html

This gets the correct screen to pop up after a user selects an answer. It also sets a timeout for when the page should change. Behind the scenes it is also changing a players score.
Review the changes to the domUpdates file.
Pull down changes and check for bugs or broken behavior.
We need to get the changes to a players score reflected on the DOM.

Incorporate correct/incorrect answer screen

---

src/Clue.js
src/domUpdates.js

I was able to get the answers to randomly populate so that the correct answer is not always in the same spot. I also fixed buggy behavior where the correct answer would evaluate to incorrect using toUpperCase().
Review the domUpdates file and Clue class file changes.
Pull down changes and check for buggy or broken behavior.
We need to incorporate wager and daily double functionality.

Answer evaluation part 2

---

src/css/base.scss

Refactor CSS code by consolidating and alphabetizing
Open base.css file
Overlook base.css to confirm changes
None

Alphabetize css

---

src/Game.js
src/domUpdates.js

This adds logic for the final round.
Review changes to the domUpdates file.
Pull down changes and test for bugs.
We need to consider refactoring redundant functions and making things more dynamic.

Final jeopardy

---

README.md
src/css/base.scss
src/domUpdates.js
src/index.html
src/index.js

Style winning player message & refactor spacing
Run program and access style
Play game until the end and observe styling on winning message
None

Style winning message

---

src/domUpdates.js
src/index.html

This fixes accessibility issues within the dev tools audit and removes console.logs

Finishing touches

---

src/DailyDouble.js
src/Game.js
src/Player.js
src/Round.js
src/css/base.scss
src/index.html
src/index.js
test/DailyDouble-test.js
test/clue-test.js
test/game-test.js
test/player-test.js
test/round-test.js

This fixes all the errors from linting that I was able to. It also fixes MOST bugs with final jeopardy

Fix most linting errors and buggy behavior wioth final jeopardy
